apiVersion: apps/v1
kind: Deployment
metadata:
  name: autosre-backend
  namespace: autosre
  labels:
    app: autosre-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: autosre-backend
  template:
    metadata:
      labels:
        app: autosre-backend
    spec:
      containers:
        - name: backend
          image: autosre-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: LOG_LEVEL
              value: "INFO"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: autosre-backend-service
  namespace: autosre
spec:
  selector:
    app: autosre-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
